In [2]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,5]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([5]),dtype=tf.float32)

multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.sigmoid(multiply1)

w_output = tf.Variable(tf.random_normal([5,1]))
output = tf.sigmoid(tf.matmul(z,w_output))

cost = tf.reduce_mean((y*tf.log(output)+(1-y)*tf.log(1-output))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)
#cost = tf.reduce_mean(tf.square(y - output))
#optimizer = tf.train.AdamOptimizer(0.001).minimize(cost)

inp = np.array([[0,0],[0,1],[1,0],[1,1]])
op = np.array([[1],[0],[0],[1]])
with tf.Session() as sess:

    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_= sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for XNOR GATE")
    result=sess.run(output,feed_dict={x:inp})
    print (result)
    print(sess.run(weights))


iteration=  0 cost=  0.855881
iteration=  1000 cost=  0.691217
iteration=  2000 cost=  0.688615
iteration=  3000 cost=  0.686177
iteration=  4000 cost=  0.683482
iteration=  5000 cost=  0.68035
iteration=  6000 cost=  0.676608
iteration=  7000 cost=  0.672069
iteration=  8000 cost=  0.666508
iteration=  9000 cost=  0.659655
iteration=  10000 cost=  0.65119
iteration=  11000 cost=  0.640741
iteration=  12000 cost=  0.627915
Validating output for XNOR GATE
[[ 0.52120328]
 [ 0.36136335]
 [ 0.57157105]
 [ 0.56896335]]
[[-0.39732867 -1.89557815 -0.44877204  0.6289804   2.47072458]
 [ 0.11723637 -0.08434558 -1.23869026  1.46985078 -2.03940439]]
